### ISSUE TITLE
Error in run_beast -a

### ISSUE THREAD

**Issue by benw1** [BEAST-Fitting/beast#132]
With the latest version, I cannot seem to generate AST lists because of an error in quantity.py in astropy.  Has anyone else seen this?

(astroconda) MacBook-Pro-2:14675_LMC-9441ne-25634 ben$ ./run_beast.py -a
Auto-detected type: fits
Auto-detected type: fits
/Users/ben/Cpipelines/metal_2/data/14675_LMC-9441ne-25634/beast/fitting/fit_metrics/__init__.py:72: UserWarning: C-code cannot be imported, did you run make? Using python code instead
  warnings.warn('C-code cannot be imported, did you run make? Using python code instead')
Auto-detected type: hd5
Auto-detected type: fits
Auto-detected type: fits
Traceback (most recent call last):
  File "./run_beast.py", line 154, in <module>
    pick_positions(filename,separation)
  File "/Users/ben/Cpipelines/metal_2/data/14675_LMC-9441ne-25634/beast/observationmodel/ast/make_ast_xy_list.py", line 39, in pick_positions
    catalog = datamodel.get_obscat(datamodel.obsfile,datamodel.distanceModulus,datamodel.filters)
  File "/Users/ben/Cpipelines/metal_2/data/14675_LMC-9441ne-25634/datamodel.py", line 290, in get_obscat
    obs = GenFluxCatalog(obsfile, filters=filters)
  File "/Users/ben/Cpipelines/metal_2/data/14675_LMC-9441ne-25634/datamodel.py", line 213, in __init__
    self.setFilters( filters )
  File "/Users/ben/Cpipelines/metal_2/data/14675_LMC-9441ne-25634/datamodel.py", line 268, in setFilters
    _, vega_flux, _ = v.getFlux(filters)
  File "/Users/ben/Cpipelines/metal_2/data/14675_LMC-9441ne-25634/beast/observationmodel/vega.py", line 55, in getFlux
    for k in filters ])
  File "/Users/ben/miniconda2/envs/astroconda/lib/python2.7/site-packages/astropy/units/quantity.py", line 1142, in __iter__
    .format(cls=self.__class__.__name__))
TypeError: 'Quantity' object with a scalar value is not iterable
(astroconda) MacBook-Pro-2:14675_LMC-9441ne-25634 ben$

**Comment by meredith-durbin** [comment]
Just checked and yes, I can reproduce the error. This seems to be an artifact of the distance modulus not being removed completely. If I put in a `print(filters)` in the `setFilters` method in `datamodel.py`, it prints 24.47 mag. Looks like the culprint is in line 39 of `observationmodel/ast/make_ast_xy_list.py`:

``` python
catalog = datamodel.get_obscat(datamodel.obsfile,datamodel.distanceModulus,datamodel.filters)
```

Unfortunately, if I remove the `datamodel.distanceModulus` parameter and try a new run, I get a new error further down:

``` python
Traceback (most recent call last):
  File "run_beast.py", line 154, in <module>
    pick_positions(filename,separation)
  File "/Users/luxemburg/beast/beast/examples/phat_small/beast/observationmodel/ast/make_ast_xy_list.py", line 47, in pick_positions
    x_positions = catalog.data[:]['x']
  File "/Users/luxemburg/beast/beast/examples/phat_small/beast/external/eztables/table.py", line 637, in __getitem__
    return np.asarray(self.data.__getitem__(self.resolve_alias(v)))
  File "/Users/luxemburg/beast/beast/examples/phat_small/beast/external/eztables/table.py", line 382, in resolve_alias
    return self._aliases.get(colname, colname)
TypeError: unhashable type: 'slice'
```

I'll look into this more after breakfast!

**Comment by meredith-durbin** [comment]
In `make_ast_xy_list` there's a lot of table data being accessed with `catalog.data[:]['column']`, where it should be `catalog.data['column'][:]`. Corrected all of that and it seems to work fine, I'll put in a pull request.
