### ISSUE TITLE
Generate spatial locations for ASTs from source density or surface brightness

### ISSUE THREAD

**Issue by karllark** [BEAST-Fitting/beast#203]
For production runs, we need to be able to generate the locations for the ASTs in the observed images based on either source density or residual surface brightness images.   This is because the main variable for the observation model is different for different objects.  For the LMC/SMC/MW, is it residual surface brightness.  For M31/M33 (and likely all UVANGST galaxies), it is source density.

Currently it is possible to generate the locations by residual surface brightness.  Need to make sure that this can also be done using the source density image.

Documentation on how to do both is needed.

**Comment by benw1** [comment]
I'm making some progress, but I have not yet been able to get the updated pick_models to work.  I think I'm missing something about the first input parameter:

chosen_seds(modelsedgrid...) 

What is modelsedgrid?  I see:

modelsedgridfile = ...
modelsedgrid = FileSEDGrid(modelsedgridfile)

Thus modelsedgrid is an object that is produced from the model grid, which seems ok, except that when pick_models tries to use it, I get:

Traceback (most recent call last):
  File "./run_beast.py", line 138, in <module>
    chosen_seds = pick_models(modelsedgrid, datamodel.filters, mag_cuts, Nfilter=Nfilters, N_stars=N_models, Nrealize=Nrealize, outfile=outfile)
  File "/Users/ben/BEAST/pub/beast/beast/examples/phat_small/beast/observationmodel/ast/make_ast_input_list.py", line 254, in pick_models
    gridf = h5py.File(sedgrid_fname)
  File "/Users/ben/miniconda3/envs/astroconda3/lib/python3.5/site-packages/h5py/_hl/files.py", line 266, in __init__
    name = filename_encode(name)
  File "/Users/ben/miniconda3/envs/astroconda3/lib/python3.5/site-packages/h5py/_hl/compat.py", line 111, in filename_encode
    filename = fspath(filename)
  File "/Users/ben/miniconda3/envs/astroconda3/lib/python3.5/site-packages/h5py/_hl/compat.py", line 42, in fspath
    + path_type.__name__)
TypeError: expected str, bytes or os.PathLike object, not SpectralGrid

This makes it look like maybe pick_models needs a string.   I tried handing it modelsedgridfile instead, and that gets a bit farther, but still errors:

raceback (most recent call last):
  File "./run_beast.py", line 138, in <module>
    chosen_seds = pick_models(modelsedgridfile, datamodel.filters, mag_cuts, Nfilter=Nfilters, N_stars=N_models, Nrealize=Nrealize, outfile=outfile)
  File "/Users/ben/BEAST/pub/beast/beast/examples/phat_small/beast/observationmodel/ast/make_ast_input_list.py", line 261, in pick_models
    grid_cut = gridf['grid'][idxs]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/ben/miniconda3/envs/astroconda3/lib/python3.5/site-packages/h5py/_hl/dataset.py", line 476, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/Users/ben/miniconda3/envs/astroconda3/lib/python3.5/site-packages/h5py/_hl/selections.py", line 72, in select
    sel[arg]
  File "/Users/ben/miniconda3/envs/astroconda3/lib/python3.5/site-packages/h5py/_hl/selections.py", line 212, in __getitem__
    raise TypeError("PointSelection __getitem__ only works with bool arrays")
TypeError: PointSelection __getitem__ only works with bool arrays


Any suggestions for getting pick_models to work?

**Comment by karllark** [comment]
The issue is that `pick_models` is expected the modelsed grid *filename*.  Not the modelsedgrid object.   So, if you pass the filename instead, it might work.

**Comment by benw1** [comment]
I tried that, and it results in the second error described above.

**Comment by karllark** [comment]
Ah...I clearly was too fast in reading and suggesting a solution.  I do not know how to solve the 2nd error.
One random thought, is your modelsedgrid file created with the BEAST code you are using for the AST work?  Just checking.

**Comment by benw1** [comment]
Yes.  In fact, it is the example "beast_example_phat/beast_example_phat_seds.grid.hd5"

**Comment by karllark** [comment]
Humm....ok, now we need @drvdputt to comment.

**Comment by drvdputt** [comment]
I ran into this recently, but forgot to submit the fix.

See #212

**Comment by karllark** [comment]
Merged in PR #212.  
@benw1 : can you see if this fixes your problem?

**Comment by benw1** [comment]
It did!  The surface brightness stuff now appears to work and produce sensible lists.  The source density stuff also works, but is not producing sensible lists yet.  Hopefully I'll figure that out next week.

**Comment by karllark** [comment]
Great.  Looking forward to what you figure out.  :-)
