### ISSUE TITLE
Byte order problem in hdf5backend (probably h5py incompatiblity)

### ISSUE THREAD

**Issue by drvdputt** [BEAST-Fitting/beast#262]
In some cases, writeHDF raises a NotImplementedError. I tried to narrow it down and found that I was using h5py somewhere, instead of the built-in hdf backend for the SED grids. 

It was somewhere in the source code of `split_grid`. For now, a workaround (just using the built-in hdf backend) has already been included in pull request #260.

Here is some example code:

```python
from beast.physicsmodel.grid import FileSEDGrid, SpectralGrid
import beast.external.eztables as tabl
import h5py

grid_fname = 'beast_example_phat_seds_trim.grid.hd5'

# load using the existing hdf backend
g = FileSEDGrid(grid_fname, backend='hdf')

# load using h5py
g_h5 = h5py.File(grid_fname)
lamb_h5 = g_h5['lamb']
seds_h5 = g_h5['seds']
gr_h5 = g_h5['grid']

# This works
sub_g_regular_way = SpectralGrid(g.lamb, seds=g.seds[:10],
                                 grid=tabl.Table(g.grid[:10]),
                                 backend='memory')
sub_g_regular_way.writeHDF('test_regular.hd5')

# This doesn't
sub_g_other_way = SpectralGrid(lamb_h5, seds=seds_h5[:10],
                               grid=tabl.Table(gr_h5[:10]),
                               backend='memory')
sub_g_other_way.writeHDF('test_other.hd5')
```

and here is the output:

```
~/Testing/beast_byteorder_bug $ python minimal_example.py 
Auto-detected type: hd5
Warning: Table does not exists.  New table will be created
test_regular.hd5 (File) ''
Last modif.: 'Fri Oct  5 18:08:15 2018'
Object Tree: 
/ (RootGroup) ''
/grid (Table(10,)) 'grid'
/lamb (EArray(6,)) 'lamb'
/seds (EArray(10, 6)) 'seds'

Auto-detected type: hd5
Warning: Table does not exists.  New table will be created
Traceback (most recent call last):
  File "/Users/drvdputt/Repositories/beast/beast/external/eztables/backends/hdf5backend.py", line 129, in write
    t = hd5.get_node(group + tablename)
  File "/Users/drvdputt/Software/miniconda3/lib/python3.5/site-packages/tables/file.py", line 1651, in get_node
    node = self._get_node(nodepath)
  File "/Users/drvdputt/Software/miniconda3/lib/python3.5/site-packages/tables/file.py", line 1599, in _get_node
    node = self._node_manager.get_node(nodepath)
  File "/Users/drvdputt/Software/miniconda3/lib/python3.5/site-packages/tables/file.py", line 437, in get_node
    node = self.node_factory(key)
  File "/Users/drvdputt/Software/miniconda3/lib/python3.5/site-packages/tables/group.py", line 1182, in _g_load_child
    node_type = self._g_check_has_child(childname)
  File "/Users/drvdputt/Software/miniconda3/lib/python3.5/site-packages/tables/group.py", line 399, in _g_check_has_child
    % (self._v_pathname, name))
tables.exceptions.NoSuchNodeError: group ``/`` does not have a child named ``/grid``

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "minimal_example.py", line 26, in <module>
    sub_g_other_way.writeHDF('test_other.hd5')
  File "/Users/drvdputt/Repositories/beast/beast/physicsmodel/helpers/gridbackends.py", line 347, in writeHDF
    self.grid.write(fname, tablename='grid', append=True)
  File "/Users/drvdputt/Repositories/beast/beast/external/eztables/table.py", line 188, in write
    return manager().write(self, filename, **kwargs)
  File "/Users/drvdputt/Repositories/beast/beast/external/eztables/backends/hdf5backend.py", line 133, in write
    t = self.__createTable__(hd5, tab, group, tablename)
  File "/Users/drvdputt/Repositories/beast/beast/external/eztables/backends/hdf5backend.py", line 93, in __createTable__
    desc = self.descr_from_dtype(tab.dtype, shapes)
  File "/Users/drvdputt/Repositories/beast/beast/external/eztables/backends/hdf5backend.py", line 67, in descr_from_dtype
    "record arrays with mixed byteorders "
NotImplementedError: record arrays with mixed byteorders are not supported yet, sorry
Closing remaining open files:beast_example_phat_seds_trim.grid.hd5...donetest_other.hd5...donetest_other.hd5...done
```

**Comment by karllark** [comment]
Yes, there are incompatibilities between the hdf5 files written by pytables and those written by h5py.  Would be nice to use only one.  It should be h5py as it is a simpler and (at least for me) easier to use and understand.  I have been thinking about how to refactor the grid classes to make them simpler and more focused for the BEAST.

**Comment by karllark** [comment]
Should be handled by the file format rework.  Leaving open to make sure.

**Comment by karllark** [comment]
Closing as currently the workaround fixes the problem.
