### ISSUE TITLE
Cannot install in fresh environment from setup.py

### ISSUE THREAD

**Issue by Stargrazer82301** [BEAST-Fitting/beast#343]
When installing beast-master via `python setup.py install`, the following exception is raised (at the end of the whole install shpeel):

```
(beastdev) replicators:beast-master cclark$ python setup.py install
The requested path 'astropy_helpers' for importing astropy_helpers does not exist, or does not contain a copy of the astropy_helpers package.
Downloading 'astropy-helpers'; run setup.py with the --offline option to force offline installation.
/Users/cclark/Desktop/beast-master/.eggs/astropy_helpers-3.2.1-py3.7.egg/astropy_helpers/git_helpers.py:120: UserWarning: No git repository present at '/Users/cclark/Desktop/beast-master'! Using default dev version.
  'default dev version.'.format(path))
/Users/cclark/Desktop/beast-master/.eggs/astropy_helpers-3.2.1-py3.7.egg/astropy_helpers/setup_helpers.py:165: AstropyDeprecationWarning: The package argument to generate_version_py has been deprecated and will be removed in future. Specify the package name in setup.cfg instead
  'the package name in setup.cfg instead', AstropyDeprecationWarning)
/Users/cclark/Desktop/beast-master/.eggs/astropy_helpers-3.2.1-py3.7.egg/astropy_helpers/setup_helpers.py:170: AstropyDeprecationWarning: The version argument to generate_version_py has been deprecated and will be removed in future. Specify the version number in setup.cfg instead
  'the version number in setup.cfg instead', AstropyDeprecationWarning)
/Users/cclark/Desktop/beast-master/.eggs/astropy_helpers-3.2.1-py3.7.egg/astropy_helpers/setup_helpers.py:176: AstropyDeprecationWarning: The release argument to generate_version_py has been deprecated and will be removed in future. We now use the presence of the "dev" string in the version to determine whether this is a release
  'determine whether this is a release', AstropyDeprecationWarning)
/Users/cclark/Desktop/beast-master/.eggs/astropy_helpers-3.2.1-py3.7.egg/astropy_helpers/setup_helpers.py:190: AstropyDeprecationWarning: Specifying the package name using the "package_name" option in setup.cfg is deprecated - use the "name" option instead.
  'option instead.', AstropyDeprecationWarning)
/Users/cclark/Desktop/beast-master/.eggs/astropy_helpers-3.2.1-py3.7.egg/astropy_helpers/version_helpers.py:244: AstropyDeprecationWarning: The packagename argument to generate_version_py has been deprecated and will be removed in future. Specify the package name in setup.cfg instead
  'the package name in setup.cfg instead', AstropyDeprecationWarning)
/Users/cclark/Desktop/beast-master/.eggs/astropy_helpers-3.2.1-py3.7.egg/astropy_helpers/version_helpers.py:249: AstropyDeprecationWarning: The version argument to generate_version_py has been deprecated and will be removed in future. Specify the version number in setup.cfg instead
  'the version number in setup.cfg instead', AstropyDeprecationWarning)
/Users/cclark/Desktop/beast-master/.eggs/astropy_helpers-3.2.1-py3.7.egg/astropy_helpers/version_helpers.py:255: AstropyDeprecationWarning: The release argument to generate_version_py has been deprecated and will be removed in future. We now use the presence of the "dev" string in the version to determine whether this is a release
  'determine whether this is a release', AstropyDeprecationWarning)
/Users/cclark/Desktop/beast-master/.eggs/astropy_helpers-3.2.1-py3.7.egg/astropy_helpers/version_helpers.py:269: AstropyDeprecationWarning: Specifying the package name using the "package_name" option in setup.cfg is deprecated - use the "name" option instead.
  'option instead.', AstropyDeprecationWarning)
/Users/cclark/Desktop/beast-master/.eggs/astropy_helpers-3.2.1-py3.7.egg/astropy_helpers/git_helpers.py:120: UserWarning: No git repository present at '/Users/cclark/Desktop/beast-master'! Using default dev version.
  'default dev version.'.format(path))
Freezing version number to ./beast/version.py
running install
running bdist_egg
running egg_info
creating beast.egg-info
writing beast.egg-info/PKG-INFO
writing dependency_links to beast.egg-info/dependency_links.txt
writing entry points to beast.egg-info/entry_points.txt
writing requirements to beast.egg-info/requires.txt
writing top-level names to beast.egg-info/top_level.txt
writing manifest file 'beast.egg-info/SOURCES.txt'
reading manifest file 'beast.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.pxd' under directory 'beast'
warning: no files found matching '*' under directory 'cextern'
warning: no files found matching '*' under directory 'scripts'
no previously-included directories found matching 'build'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'docs/api'
warning: no files found matching 'astropy_helpers/README.rst'
warning: no files found matching 'astropy_helpers/CHANGES.rst'
warning: no files found matching 'astropy_helpers/LICENSE.rst'
warning: no files found matching '*' under directory 'astropy_helpers/licenses'
warning: no files found matching 'astropy_helpers/ah_bootstrap.py'
warning: no files found matching '*.py' under directory 'astropy_helpers/astropy_helpers'
warning: no files found matching '*.pyx' under directory 'astropy_helpers/astropy_helpers'
warning: no files found matching '*.c' under directory 'astropy_helpers/astropy_helpers'
warning: no files found matching '*.h' under directory 'astropy_helpers/astropy_helpers'
warning: no files found matching '*.rst' under directory 'astropy_helpers/astropy_helpers'
warning: no files found matching '*' under directory 'astropy_helpers/astropy_helpers.egg-info'
warning: no files found matching '*' under directory 'astropy_helpers/astropy_helpers/sphinx'
no previously-included directories found matching 'astropy_helpers/build'
no previously-included directories found matching 'astropy_helpers/astropy_helpers/tests'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.o' found anywhere in distribution
writing manifest file 'beast.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.7-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.macosx-10.7-x86_64-3.7
creating build/lib.macosx-10.7-x86_64-3.7/beast
copying beast/conftest.py -> build/lib.macosx-10.7-x86_64-3.7/beast
copying beast/config.py -> build/lib.macosx-10.7-x86_64-3.7/beast
copying beast/version.py -> build/lib.macosx-10.7-x86_64-3.7/beast
copying beast/_astropy_init.py -> build/lib.macosx-10.7-x86_64-3.7/beast
copying beast/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/beast
creating build/lib.macosx-10.7-x86_64-3.7/beast/tools
copying beast/tools/setup_batch_beast_trim.py -> build/lib.macosx-10.7-x86_64-3.7/beast/tools
copying beast/tools/merge_beast_stats.py -> build/lib.macosx-10.7-x86_64-3.7/beast/tools
copying beast/tools/condense_beast_results_spatial.py -> build/lib.macosx-10.7-x86_64-3.7/beast/tools
copying beast/tools/remove_filters.py -> build/lib.macosx-10.7-x86_64-3.7/beast/tools
copying beast/tools/simulate_obs.py -> build/lib.macosx-10.7-x86_64-3.7/beast/tools
copying beast/tools/reorder_beast_results_spatial.py -> build/lib.macosx-10.7-x86_64-3.7/beast/tools
copying beast/tools/contextManagers.py -> build/lib.macosx-10.7-x86_64-3.7/beast/tools
copying beast/tools/density_map.py -> build/lib.macosx-10.7-x86_64-3.7/beast/tools
copying beast/tools/split_catalog_using_map.py -> build/lib.macosx-10.7-x86_64-3.7/beast/tools
copying beast/tools/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/beast/tools
copying beast/tools/binningAxis.py -> build/lib.macosx-10.7-x86_64-3.7/beast/tools
copying beast/tools/subdivide_obscat_by_source_density.py -> build/lib.macosx-10.7-x86_64-3.7/beast/tools
copying beast/tools/split_asts_by_source_density.py -> build/lib.macosx-10.7-x86_64-3.7/beast/tools
copying beast/tools/trim_many_via_obsdata.py -> build/lib.macosx-10.7-x86_64-3.7/beast/tools
copying beast/tools/subgridding_tools.py -> build/lib.macosx-10.7-x86_64-3.7/beast/tools
copying beast/tools/split_ast_input_file.py -> build/lib.macosx-10.7-x86_64-3.7/beast/tools
copying beast/tools/setup_batch_beast_fit.py -> build/lib.macosx-10.7-x86_64-3.7/beast/tools
copying beast/tools/pbar.py -> build/lib.macosx-10.7-x86_64-3.7/beast/tools
copying beast/tools/helpers.py -> build/lib.macosx-10.7-x86_64-3.7/beast/tools
copying beast/tools/create_background_density_map.py -> build/lib.macosx-10.7-x86_64-3.7/beast/tools
copying beast/tools/verify_params.py -> build/lib.macosx-10.7-x86_64-3.7/beast/tools
copying beast/tools/get_libfiles.py -> build/lib.macosx-10.7-x86_64-3.7/beast/tools
copying beast/tools/decorators.py -> build/lib.macosx-10.7-x86_64-3.7/beast/tools
creating build/lib.macosx-10.7-x86_64-3.7/beast/fitting
copying beast/fitting/fit.py -> build/lib.macosx-10.7-x86_64-3.7/beast/fitting
copying beast/fitting/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/beast/fitting
copying beast/fitting/trim_grid.py -> build/lib.macosx-10.7-x86_64-3.7/beast/fitting
copying beast/fitting/pdf1d.py -> build/lib.macosx-10.7-x86_64-3.7/beast/fitting
creating build/lib.macosx-10.7-x86_64-3.7/beast/tests
copying beast/tests/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/beast/tests
copying beast/tests/helpers.py -> build/lib.macosx-10.7-x86_64-3.7/beast/tests
copying beast/tests/setup_package.py -> build/lib.macosx-10.7-x86_64-3.7/beast/tests
creating build/lib.macosx-10.7-x86_64-3.7/beast/observationmodel
copying beast/observationmodel/observations.py -> build/lib.macosx-10.7-x86_64-3.7/beast/observationmodel
copying beast/observationmodel/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/beast/observationmodel
copying beast/observationmodel/extra_filters.py -> build/lib.macosx-10.7-x86_64-3.7/beast/observationmodel
copying beast/observationmodel/phot.py -> build/lib.macosx-10.7-x86_64-3.7/beast/observationmodel
copying beast/observationmodel/vega.py -> build/lib.macosx-10.7-x86_64-3.7/beast/observationmodel
creating build/lib.macosx-10.7-x86_64-3.7/beast/plotting
copying beast/plotting/plot_stats_check.py -> build/lib.macosx-10.7-x86_64-3.7/beast/plotting
copying beast/plotting/plot_mag_hist.py -> build/lib.macosx-10.7-x86_64-3.7/beast/plotting
copying beast/plotting/plot_filters.py -> build/lib.macosx-10.7-x86_64-3.7/beast/plotting
copying beast/plotting/plot_param_vs_chi2min.py -> build/lib.macosx-10.7-x86_64-3.7/beast/plotting
copying beast/plotting/plot_chi2_hist.py -> build/lib.macosx-10.7-x86_64-3.7/beast/plotting
copying beast/plotting/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/beast/plotting
copying beast/plotting/plot_good_bad.py -> build/lib.macosx-10.7-x86_64-3.7/beast/plotting
copying beast/plotting/plot_cmd.py -> build/lib.macosx-10.7-x86_64-3.7/beast/plotting
copying beast/plotting/plot_indiv_fit.py -> build/lib.macosx-10.7-x86_64-3.7/beast/plotting
copying beast/plotting/plot_region_diags.py -> build/lib.macosx-10.7-x86_64-3.7/beast/plotting
copying beast/plotting/plot_cmd_with_fits.py -> build/lib.macosx-10.7-x86_64-3.7/beast/plotting
copying beast/plotting/beastplotlib.py -> build/lib.macosx-10.7-x86_64-3.7/beast/plotting
creating build/lib.macosx-10.7-x86_64-3.7/beast/examples
copying beast/examples/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/beast/examples
creating build/lib.macosx-10.7-x86_64-3.7/beast/external
copying beast/external/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/beast/external
creating build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel
copying beast/physicsmodel/grid.py -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel
copying beast/physicsmodel/prior_weights.py -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel
copying beast/physicsmodel/prior_weights_dust.py -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel
copying beast/physicsmodel/grid_and_prior_weights.py -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel
copying beast/physicsmodel/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel
copying beast/physicsmodel/create_project_dir.py -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel
copying beast/physicsmodel/creategrid.py -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel
copying beast/physicsmodel/grid_weights.py -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel
copying beast/physicsmodel/model_grid.py -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel
creating build/lib.macosx-10.7-x86_64-3.7/beast/tools/tests
copying beast/tools/tests/test_subgridding_tools.py -> build/lib.macosx-10.7-x86_64-3.7/beast/tools/tests
copying beast/tools/tests/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/beast/tools/tests
creating build/lib.macosx-10.7-x86_64-3.7/beast/fitting/tests
copying beast/fitting/tests/test_trim_grid.py -> build/lib.macosx-10.7-x86_64-3.7/beast/fitting/tests
copying beast/fitting/tests/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/beast/fitting/tests
copying beast/fitting/tests/test_fit_grid.py -> build/lib.macosx-10.7-x86_64-3.7/beast/fitting/tests
creating build/lib.macosx-10.7-x86_64-3.7/beast/fitting/fit_metrics
copying beast/fitting/fit_metrics/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/beast/fitting/fit_metrics
copying beast/fitting/fit_metrics/common.py -> build/lib.macosx-10.7-x86_64-3.7/beast/fitting/fit_metrics
copying beast/fitting/fit_metrics/likelihood.py -> build/lib.macosx-10.7-x86_64-3.7/beast/fitting/fit_metrics
creating build/lib.macosx-10.7-x86_64-3.7/beast/observationmodel/tests
copying beast/observationmodel/tests/test_toothpick_noisemodel.py -> build/lib.macosx-10.7-x86_64-3.7/beast/observationmodel/tests
copying beast/observationmodel/tests/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/beast/observationmodel/tests
copying beast/observationmodel/tests/test_ast_input_list.py -> build/lib.macosx-10.7-x86_64-3.7/beast/observationmodel/tests
copying beast/observationmodel/tests/test_simobs.py -> build/lib.macosx-10.7-x86_64-3.7/beast/observationmodel/tests
creating build/lib.macosx-10.7-x86_64-3.7/beast/observationmodel/noisemodel
copying beast/observationmodel/noisemodel/splinter.py -> build/lib.macosx-10.7-x86_64-3.7/beast/observationmodel/noisemodel
copying beast/observationmodel/noisemodel/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/beast/observationmodel/noisemodel
copying beast/observationmodel/noisemodel/toothpick.py -> build/lib.macosx-10.7-x86_64-3.7/beast/observationmodel/noisemodel
copying beast/observationmodel/noisemodel/absflux_covmat.py -> build/lib.macosx-10.7-x86_64-3.7/beast/observationmodel/noisemodel
copying beast/observationmodel/noisemodel/helpers.py -> build/lib.macosx-10.7-x86_64-3.7/beast/observationmodel/noisemodel
copying beast/observationmodel/noisemodel/noisemodel.py -> build/lib.macosx-10.7-x86_64-3.7/beast/observationmodel/noisemodel
copying beast/observationmodel/noisemodel/trunchen.py -> build/lib.macosx-10.7-x86_64-3.7/beast/observationmodel/noisemodel
copying beast/observationmodel/noisemodel/generic_noisemodel.py -> build/lib.macosx-10.7-x86_64-3.7/beast/observationmodel/noisemodel
creating build/lib.macosx-10.7-x86_64-3.7/beast/observationmodel/ast
copying beast/observationmodel/ast/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/beast/observationmodel/ast
copying beast/observationmodel/ast/make_ast_input_list.py -> build/lib.macosx-10.7-x86_64-3.7/beast/observationmodel/ast
copying beast/observationmodel/ast/make_ast_xy_list.py -> build/lib.macosx-10.7-x86_64-3.7/beast/observationmodel/ast
creating build/lib.macosx-10.7-x86_64-3.7/beast/plotting/tests
copying beast/plotting/tests/test_plots.py -> build/lib.macosx-10.7-x86_64-3.7/beast/plotting/tests
copying beast/plotting/tests/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/beast/plotting/tests
creating build/lib.macosx-10.7-x86_64-3.7/beast/external/eztables
copying beast/external/eztables/registered_backends.py -> build/lib.macosx-10.7-x86_64-3.7/beast/external/eztables
copying beast/external/eztables/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/beast/external/eztables
copying beast/external/eztables/setup.py -> build/lib.macosx-10.7-x86_64-3.7/beast/external/eztables
copying beast/external/eztables/table.py -> build/lib.macosx-10.7-x86_64-3.7/beast/external/eztables
creating build/lib.macosx-10.7-x86_64-3.7/beast/external/eztables/core
copying beast/external/eztables/core/compatibility.py -> build/lib.macosx-10.7-x86_64-3.7/beast/external/eztables/core
copying beast/external/eztables/core/odict.py -> build/lib.macosx-10.7-x86_64-3.7/beast/external/eztables/core
copying beast/external/eztables/core/sqlhelpers.py -> build/lib.macosx-10.7-x86_64-3.7/beast/external/eztables/core
copying beast/external/eztables/core/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/beast/external/eztables/core
copying beast/external/eztables/core/tableheader.py -> build/lib.macosx-10.7-x86_64-3.7/beast/external/eztables/core
copying beast/external/eztables/core/helpers.py -> build/lib.macosx-10.7-x86_64-3.7/beast/external/eztables/core
copying beast/external/eztables/core/columnheader.py -> build/lib.macosx-10.7-x86_64-3.7/beast/external/eztables/core
copying beast/external/eztables/core/decorators.py -> build/lib.macosx-10.7-x86_64-3.7/beast/external/eztables/core
creating build/lib.macosx-10.7-x86_64-3.7/beast/external/eztables/backends
copying beast/external/eztables/backends/fitsbackend.py -> build/lib.macosx-10.7-x86_64-3.7/beast/external/eztables/backends
copying beast/external/eztables/backends/hdf5backend.py -> build/lib.macosx-10.7-x86_64-3.7/beast/external/eztables/backends
copying beast/external/eztables/backends/asciibackend.py -> build/lib.macosx-10.7-x86_64-3.7/beast/external/eztables/backends
copying beast/external/eztables/backends/registered_backends.py -> build/lib.macosx-10.7-x86_64-3.7/beast/external/eztables/backends
copying beast/external/eztables/backends/votablebackend.py -> build/lib.macosx-10.7-x86_64-3.7/beast/external/eztables/backends
copying beast/external/eztables/backends/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/beast/external/eztables/backends
copying beast/external/eztables/backends/sqlbackend.py -> build/lib.macosx-10.7-x86_64-3.7/beast/external/eztables/backends
copying beast/external/eztables/backends/latexbackend.py -> build/lib.macosx-10.7-x86_64-3.7/beast/external/eztables/backends
copying beast/external/eztables/backends/jsonbackend.py -> build/lib.macosx-10.7-x86_64-3.7/beast/external/eztables/backends
copying beast/external/eztables/backends/basebackend.py -> build/lib.macosx-10.7-x86_64-3.7/beast/external/eztables/backends
creating build/lib.macosx-10.7-x86_64-3.7/beast/external/eztables/astro
copying beast/external/eztables/astro/astrotable.py -> build/lib.macosx-10.7-x86_64-3.7/beast/external/eztables/astro
copying beast/external/eztables/astro/astrohelpers.py -> build/lib.macosx-10.7-x86_64-3.7/beast/external/eztables/astro
copying beast/external/eztables/astro/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/beast/external/eztables/astro
creating build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/dust
copying beast/physicsmodel/dust/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/dust
copying beast/physicsmodel/dust/extinction.py -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/dust
creating build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/tests
copying beast/physicsmodel/tests/test_gen_spectralgrid.py -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/tests
copying beast/physicsmodel/tests/test_extinguished_sed_grid.py -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/tests
copying beast/physicsmodel/tests/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/tests
creating build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/stars
copying beast/physicsmodel/stars/isochrone.py -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/stars
copying beast/physicsmodel/stars/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/stars
copying beast/physicsmodel/stars/stellib.py -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/stars
copying beast/physicsmodel/stars/simpletable.py -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/stars
creating build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/helpers
copying beast/physicsmodel/helpers/gridhelpers.py -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/helpers
copying beast/physicsmodel/helpers/gridbackends.py -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/helpers
copying beast/physicsmodel/helpers/hdfstore.py -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/helpers
copying beast/physicsmodel/helpers/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/helpers
copying beast/physicsmodel/helpers/path.py -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/helpers
creating build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/dust/tests
copying beast/physicsmodel/dust/tests/test_extinction.py -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/dust/tests
copying beast/physicsmodel/dust/tests/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/dust/tests
creating build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/stars/include
copying beast/physicsmodel/stars/include/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/stars/include
copying beast/physicsmodel/stars/include/setup.py -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/stars/include
creating build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/stars/tests
copying beast/physicsmodel/stars/tests/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/stars/tests
copying beast/physicsmodel/stars/tests/test_spectral_grid.py -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/stars/tests
copying beast/physicsmodel/stars/tests/test_padova_isochrone_download.py -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/stars/tests
creating build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/stars/ezmist
copying beast/physicsmodel/stars/ezmist/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/stars/ezmist
copying beast/physicsmodel/stars/ezmist/mist.py -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/stars/ezmist
creating build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/stars/kurucz
copying beast/physicsmodel/stars/kurucz/generate.py -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/stars/kurucz
copying beast/physicsmodel/stars/kurucz/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/stars/kurucz
creating build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/stars/ezpadova
copying beast/physicsmodel/stars/ezpadova/parsec.py -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/stars/ezpadova
copying beast/physicsmodel/stars/ezpadova/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/stars/ezpadova
copying beast/physicsmodel/stars/ezpadova/parsec.json -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/stars/ezpadova
copying beast/physicsmodel/stars/ezmist/mist.json -> build/lib.macosx-10.7-x86_64-3.7/beast/physicsmodel/stars/ezmist
creating build/lib.macosx-10.7-x86_64-3.7/beast/plotting/tests/baseline
copying beast/plotting/tests/baseline/test_indiv_plot.png -> build/lib.macosx-10.7-x86_64-3.7/beast/plotting/tests/baseline
copying beast/tests/coveragerc -> build/lib.macosx-10.7-x86_64-3.7/beast/tests
running build_ext
Traceback (most recent call last):
  File "setup.py", line 158, in <module>
    **package_info
  File "/Users/cclark/Soft/anaconda3/envs/beastdev/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/Users/cclark/Soft/anaconda3/envs/beastdev/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/cclark/Soft/anaconda3/envs/beastdev/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/cclark/Soft/anaconda3/envs/beastdev/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/cclark/Soft/anaconda3/envs/beastdev/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/Users/cclark/Soft/anaconda3/envs/beastdev/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/Users/cclark/Soft/anaconda3/envs/beastdev/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/cclark/Soft/anaconda3/envs/beastdev/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/cclark/Soft/anaconda3/envs/beastdev/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/Users/cclark/Soft/anaconda3/envs/beastdev/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/Users/cclark/Soft/anaconda3/envs/beastdev/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/cclark/Soft/anaconda3/envs/beastdev/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/cclark/Soft/anaconda3/envs/beastdev/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/Users/cclark/Soft/anaconda3/envs/beastdev/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/Users/cclark/Soft/anaconda3/envs/beastdev/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/cclark/Soft/anaconda3/envs/beastdev/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/cclark/Desktop/beast-master/.eggs/astropy_helpers-3.2.1-py3.7.egg/astropy_helpers/commands/build_ext.py", line 131, in run
    np_include = get_numpy_include_path()
  File "/Users/cclark/Desktop/beast-master/.eggs/astropy_helpers-3.2.1-py3.7.egg/astropy_helpers/utils.py", line 60, in get_numpy_include_path
    import numpy
ModuleNotFoundError: No module named 'numpy'
```

**Comment by karllark** [comment]
This is a bit surprising to me.  Was astropy installed before running the beast install?  Astropy depends on numpy and so it should have been installed if astropy was installed.

**Comment by Stargrazer82301** [comment]
If memory serves I was installing it on a fresh anaconda (not astroconda) environment, so nothing would have been installed?

**Comment by karllark** [comment]
Then the error is expected.  You will need to install astropy and a couple of other packages from a fresh install for the beast to work.  Documented in https://beast.readthedocs.io/en/latest/install.html.

**Comment by Stargrazer82301** [comment]
Interesting; I'm not sure I've come across a previous instance of a package requiring other packages in order to install (as opposed to just run) - not sure the documentation makes that distinction?

**Comment by karllark** [comment]
The difference is if you install beast via "python setup.py install" versus pip install. I believe the pip install will pull in the dependencies, but the python way will not.  Not sure, but that is what I thought.

**Comment by Stargrazer82301** [comment]
But I thought that normally, when installing via "python setup.py install", errors due to absent dependencies won't appear during install, but instead will appear only once you actually try to run something.

**Comment by karllark** [comment]
You are generally correct, expect in some cases where code is compiled I think.  Hence why it is happening in this case.
