### ISSUE TITLE
SEDGrid/SpecGrid can't read hd5 (seds/noisemodel) files created before updating SEDGrid/SpecGrid by switching from tables to astropy.table

### ISSUE THREAD

**Issue by galaxyumi** [BEAST-Fitting/beast#638]
I have a physicsmodel grid file created before we updated SEDGrid/SpecGrid (by switching from tables to astropy.table) and am trying to generate an observational model grid using that physicsmodel grid file and the resulting ASTs. However, it seems like the SEDGrid can't read the old hd5 files due to some incompatibility issues. Below is the error message that I got when trying "python -m beast.tools.run.create_obsmodel beast_settings.txt --nsubs=1". 

Traceback (most recent call last):
  File "/Users/ychoi/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/ychoi/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/ychoi/Research/beast/beast/tools/run/create_obsmodel.py", line 247, in <module>
    subset=args.subset,
  File "/Users/ychoi/Research/beast/beast/tools/run/create_obsmodel.py", line 106, in create_obsmodel
    parallel_wrapper(gen_obsmodel, input_list, nprocs=nprocs)
  File "/Users/ychoi/Research/beast/beast/tools/run/helper_functions.py", line 61, in parallel_wrapper
    r = function(*a)
  File "/Users/ychoi/Research/beast/beast/tools/run/create_obsmodel.py", line 190, in gen_obsmodel
    modelsedgrid = SEDGrid(modelsedgridfile)
  File "/Users/ychoi/Research/beast/beast/physicsmodel/grid.py", line 81, in __init__
    self._backend = MemoryBackend(*args, **kwargs)
  File "/Users/ychoi/Research/beast/beast/physicsmodel/helpers/gridbackends.py", line 299, in __init__
    self._from_File(lamb)
  File "/Users/ychoi/Research/beast/beast/physicsmodel/helpers/gridbackends.py", line 379, in _from_File
    self.grid = read_table_hdf5(s["grid"])
  File "/Users/ychoi/anaconda3/lib/python3.7/site-packages/astropy/io/misc/hdf5.py", line 184, in read_table_hdf5
    table.meta.update(input.attrs)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/ychoi/anaconda3/lib/python3.7/site-packages/h5py/_hl/attrs.py", line 81, in __getitem__
    attr.read(arr, mtype=htype)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5a.pyx", line 355, in h5py.h5a.AttrID.read
  File "h5py/_proxy.pyx", line 36, in h5py._proxy.attr_rw
OSError: Unable to read attribute (no appropriate function for conversion path)

**Comment by karllark** [comment]
What version of h5py do you have?  Preliminary googling says this may be an issue with older h5py version (maybe fixed in h5py version 2.10).

**Comment by karllark** [comment]
See.  https://github.com/h5py/h5py/issues/719

**Comment by karllark** [comment]
Of course, one straightforward solution is to re-calculate the physicsmodel with the latest BEAST version.

**Comment by galaxyumi** [comment]
Indeed upgrading h5py to version 2.10 fixed the problem!

**Comment by karllark** [comment]
Great.  Does this close this issue?

**Comment by galaxyumi** [comment]
Yes!
