### ISSUE TITLE
returning error when *_beast_info.asdf exists

### ISSUE THREAD

**Issue by galaxyumi** [BEAST-Fitting/beast#639]
When re-creating the physicsmodel grid, BEAST returns the following error message when a *_beast_info.asdf file already exists. 

Traceback (most recent call last):
  File "/Users/ychoi/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/ychoi/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/ychoi/Research/beast/beast/tools/run/create_physicsmodel.py", line 300, in <module>
    subset=args.subset,
  File "/Users/ychoi/Research/beast/beast/tools/run/create_physicsmodel.py", line 78, in create_physicsmodel
    z=settings.z,
  File "/Users/ychoi/Research/beast/beast/physicsmodel/model_grid.py", line 90, in make_iso_table
    add_to_beast_info_file(info_fname, info)
  File "/Users/ychoi/Research/beast/beast/tools/beast_info.py", line 30, in add_to_beast_info_file
    af = asdf.AsdfFile(tree)
  File "/Users/ychoi/anaconda3/lib/python3.7/site-packages/asdf/asdf.py", line 159, in __init__
    self.tree = tree
  File "/Users/ychoi/anaconda3/lib/python3.7/site-packages/asdf/asdf.py", line 409, in tree
    self._validate(asdf_object, custom=bool(tree))
  File "/Users/ychoi/anaconda3/lib/python3.7/site-packages/asdf/asdf.py", line 438, in _validate
    tree, self)
  File "/Users/ychoi/anaconda3/lib/python3.7/site-packages/asdf/yamlutil.py", line 237, in custom_tree_to_tagged_tree
    _context=ctx._tree_modification_context,
  File "/Users/ychoi/anaconda3/lib/python3.7/site-packages/asdf/treeutil.py", line 406, in walk_and_modify
    return _recurse(top)
  File "/Users/ychoi/anaconda3/lib/python3.7/site-packages/asdf/treeutil.py", line 393, in _recurse
    result = _handle_children(result, json_id)
  File "/Users/ychoi/anaconda3/lib/python3.7/site-packages/asdf/treeutil.py", line 365, in _handle_children
    return _handle_generator(result)
  File "/Users/ychoi/anaconda3/lib/python3.7/site-packages/asdf/treeutil.py", line 263, in _handle_generator
    result = next(generator)
  File "/Users/ychoi/anaconda3/lib/python3.7/site-packages/asdf/treeutil.py", line 291, in _handle_mapping
    value = _recurse(value, json_id)
  File "/Users/ychoi/anaconda3/lib/python3.7/site-packages/asdf/treeutil.py", line 392, in _recurse
    result = _handle_callback(node, json_id)
  File "/Users/ychoi/anaconda3/lib/python3.7/site-packages/asdf/treeutil.py", line 270, in _handle_callback
    result = callback(node)
  File "/Users/ychoi/anaconda3/lib/python3.7/site-packages/asdf/yamlutil.py", line 227, in walker
    return tag.to_tree_tagged(node, ctx)
  File "/Users/ychoi/anaconda3/lib/python3.7/site-packages/asdf/types.py", line 314, in to_tree_tagged
    obj = cls.to_tree(node, ctx)
  File "/Users/ychoi/anaconda3/lib/python3.7/site-packages/asdf/tags/core/ndarray.py", line 417, in to_tree
    if any(stride == 0 for stride in data.strides):
  File "/Users/ychoi/anaconda3/lib/python3.7/site-packages/asdf/tags/core/ndarray.py", line 362, in __getattr__
    return getattr(self._make_array(), attr)
  File "/Users/ychoi/anaconda3/lib/python3.7/site-packages/asdf/tags/core/ndarray.py", line 268, in _make_array
    shape, dtype, block.data,
  File "/Users/ychoi/anaconda3/lib/python3.7/site-packages/asdf/block.py", line 1170, in data
    "ASDF file has already been closed. "
**OSError: ASDF file has already been closed. Can not get the data.**

**Comment by karllark** [comment]
This will be fixed by this PR -> https://github.com/BEAST-Fitting/beast/pull/634.  I've just made the change I asked for so that this PR could be merged after the tests pass.
